# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ASTR Webpage Builder

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      VITE_BASE: /ArknightsStoryTextReader/

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/checkout@v2
      with:
        repository: 050644zf/ArknightsStoryTextReader
        ref: gh-pages
        path: gh-pages
        token: ${{secrets.PAT}}
    - uses: actions/setup-node@v4.0.3
      with:
        node-version: '22.14.0'
    - run: |
        cd reader
        npm ci
        npm run build
        echo "Build Completed!"
        cd ..
        cp ./reader/dist/* ./gh-pages -r
        echo "File Transfer Completed!"
        cd gh-pages
        git config --global user.email ${{secrets.EMAIL}}
        git config --global user.name ${{secrets.USERNAME}}
        git add -A
        git commit --allow-empty -m 'Build'
        git push
        echo "Build Pushed!"
    
    
