# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ASTR Webpage Builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: 050644zf/ArknightsStoryTextReader
        ref: gh-pages
        path: gh-pages
        token: ${{secrets.PAT}}
    - uses: actions/setup-node@v2
      with:
        node-version: '17.5.0'
    - run: |
        cd reader
        npm ci
        npm run build
        cd ..
        cp .\reader\dist\* .\gh-pages -r
        cd gh-pages
        git add -A
        git commit -m 'Build'
        git push
    
    
