# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ASTR Webpage PR Test

on:
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      VITE_BASE: /ArknightsStoryTextReader/

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.9.0'
    - run: |
        cd reader
        npm ci
        npm run build
        echo "Build Completed!"
    
    
